# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: dynamic_sas_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U django -d dynamic_sas_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Inyectamos la SECRET_KEY que definiste en Settings → Secrets
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      # URL de la base de datos de pruebas
      DATABASE_URL: postgres://django:django@localhost:5432/dynamic_sas_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=.

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

